version: '3'
#**************************************************************
# integration level test agents                                *
#***************************************************************

services:
  #*************************************************************
  # acapy_plugin_agent: acapy agent loaded with plugin         *
  # for testing                                                *
  #*************************************************************

  acapy_plugin_agent:
    image: acapy-plugin-toolbox
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "3001:3001"
    command: start -it http 0.0.0.0 3000 -ot http -e http://acapy_plugin_agent:3000 --admin 0.0.0.0 3001 --admin-insecure-mode --plugin acapy_plugin_toolbox --log-level debug --genesis-url https://raw.githubusercontent.com/Indicio-tech/indicio-network/master/genesis_files/pool_transactions_testnet_genesis --wallet-type indy --wallet-name default --wallet-key "insecure, for use in testing only" --auto-provision --auto-ping-connection

  #*************************************************************
  # tester: drives tests for acapy_plugin_toolbox in a         *
  # "Juggernaut" fashion!                                      *
  #*************************************************************

  tests:
    container_name: juggernaut
    command: -k test_holder_credential_exchange
    build:
      context: .
      dockerfile: ./Dockerfile.test.runner
    environment:
      - WAIT_BEFORE_HOSTS=3
      - WAIT_HOSTS=acapy_plugin_agent:3000
      - WAIT_HOSTS_TIMEOUT=60
      - WAIT_SLEEP_INTERVAL=1
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - AGENT_HOST=acapy_plugin_agent
      - AGENT_PORT=3000
      - AGENT_BACKCHANNEL_PORT=3001
      - SUITE_HOST=tests
      - SUITE_PORT=3002
    depends_on:
      - acapy_plugin_agent
